### PR TITLE
Add social preview image

### PR DESCRIPTION
**Pull request by maxulysse**
- Add social preview image

## PR checklist
 - [ ] This comment contains a description of changes (with reason)
 - [ ] If you've fixed a bug or added code that should be tested, add tests!
 - [ ] If necessary, also make a PR on the [nf-core/neutronstar branch on the nf-core/test-datasets repo]( https://github.com/nf-core/test-datasets/pull/new/nf-core/neutronstar)
 - [ ] Ensure the test suite passes (`nextflow run . -profile test,docker`).
 - [ ] Make sure your code lints (`nf-core lint .`).
 - [ ] Documentation in `docs` is updated
 - [ ] `CHANGELOG.md` is updated
 - [ ] `README.md` is updated

**Learn more about contributing:** https://github.com/nf-core/neutronstar/tree/master/.github/CONTRIBUTING.md

### CODE REVIEW

**Comment by remiolsen** [comment]
@MaxUlysse Make a new PR to `dev` perhaps?

**Comment by maxulysse** [comment]
Sorry, did not notice it was to master and not dev, so I reopened it and use the right branch

**Comment by remiolsen** [comment]
Thanks @MaxUlysse. I'm not sure what this is for but it looks cool :+1:

I'm guessing the linting stuff will be fixed in the new template update, or?

**Comment by maxulysse** [comment]
In fact the social preview is already set up, but now, all pipelines have the source files to update it as well.
Linting will indeed be fixed with the new sync

**Review by remiolsen — APPROVED** [review]

**Pull request merged**
